### ISSUE TITLE
Gateway + CLN Docker Deployment Option

### ISSUE THREAD

**Issue by Kodylow** [fedimint/fedimint-docker#7]
Doing the LND gateway deployments has been super annoying since we're not surfacing and handling errors properly for unsynced nodes to and through the gateway, @elsirion recommended we add the CLN deployment option since we can use esplora with it, so we need to build out the docker image for gatewayd binary + plugin as part of the fedimint CI. then when that's ready add it as a configuration option here

**Comment by elsirion** [comment]
I think we have this now: https://github.com/fedimint/fedimint-docker/blob/master/configurations/gateway_mainnet_cln_local/docker-compose.yaml
